java_test(
    name = "statement_parser_test",
    size = "small",
    srcs = ["StatementParserTest.java"],
    test_class = "me.horlick.db.StatementParserTest",
    deps = [
        "//java/me/horlick/db",
        "@hamcrest_core//jar",
        "@junit//jar",
        "@org_mockito_mockito//jar",
    ],
)
