package(default_visibility = ["//visibility:public"])

java_library(
    name = "db",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_errorprone_error_prone_annotations//jar",
        "@guava//jar",
        "@org_slf4j_slf4j_api//jar",
        "@protobuf//:protobuf_java",
    ],
)
